DemoWebApp/src/DemoWebApp/Controllers/BasicsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoWebApp.Controllers
{
    public class BasicsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AspNetCore()
        {
            return View();
        }

        public IActionResult Structure()
        {
            return View();
        }

        public IActionResult EF7()
        {
            return View();
        }

        public IActionResult EFCore()
        {
            return View();
        }

        public IActionResult TagHelpers()
        {
            return View();
        }

        public IActionResult Areas()
        {
            return View();
        }

        public IActionResult Controllers()
        {
            return View();
        }

        public IActionResult Migrations()
        {
            return View();
        }

        public IActionResult Logging()
        {
            return View();
        }
    }
}

DemoWebApp/src/DemoWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] | OTS 2016 | Modern Web</title>
    <meta name="description" content="OTS 2016 Modern Web Technologies created by ADORA-MED | DEMO">
    <meta name="author" content="ADORA-MED">
    <meta name="robots" content="noindex, nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400italic,600,700%7COpen+Sans:300,400,400italic,600,700">

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/lib/simple-line-icons/css/simple-line-icons.css" />
        <link rel="stylesheet" href="~/css/theme.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div id="page-container" class="sidebar-l sidebar-o side-scroll header-navbar-fixed">
        <aside id="side-overlay">
            <div id="side-overlay-scroll">
                <div class="side-header side-content">
                    <button class="btn btn-default pull-right" type="button" data-toggle="layout" data-action="side_overlay_close">
                        <i class="fa fa-times"></i>
                    </button>
                    <span>
                        <span class="font-w600 push-10-l">Anonymous</span>
                    </span>
                </div>
            </div>
        </aside>
        <nav id="sidebar">
            <div class="sidebar-content">
                <div class="side-header side-content bg-white-op">
                    <button class="btn btn-link text-gray pull-right hidden-md hidden-lg" type="button" data-toggle="layout" data-action="sidebar_close">
                        <i class="fa fa-times"></i>
                    </button>
                    <div class="btn-group pull-right">
                        <button class="btn btn-link text-gray dropdown-toggle" data-toggle="dropdown" type="button">
                            <i class="si si-drop"></i>
                        </button>
                    </div>
                    <a class="h5 text-white" href="@Url.Action("Index", "Home", new { area = "" })">
                        <i class="fa fa-home text-primary"></i> <span class="h4 font-w600 sidebar-mini-hide">OTS 2016</span>
                    </a>
                </div>
                <div class="side-content">
                    <ul class="nav-main">
                        <li>
                            <a data-tmp="Home" asp-action="Index" asp-controller="Home" asp-area=""><i class="icon icon-speedometer"></i><span class="sidebar-mini-hide" />Home</a>
                        </li>
                        <li>
                            <a asp-action="Index" asp-controller="Home" asp-area="FilmFanatic"><i class="fa fa-asterisk"></i><span class="sidebar-mini-hide" />FilmFanatic</a>
                        </li>
                        <li class="nav-main-heading"><span class="sidebar-mini-hide">Basics</span></li>
                        <li>
                            <a data-tmp="AspNetCore" asp-action="AspNetCore" asp-controller="Basics" asp-area=""><i class="icon icon-energy"></i><span class="sidebar-mini-hide" />ASP.NET Core</a>
                        </li>
                        <li>
                            <a data-tmp="Structure" asp-action="Structure" asp-controller="Basics" asp-area=""><i class="fa fa-code"></i><span class="sidebar-mini-hide" />Project Structure</a>
                        </li>
                        <li>
                            <a data-tmp="Areas" asp-action="Areas" asp-controller="Basics" asp-area=""><i class="icon icon-compass"></i><span class="sidebar-mini-hide" />Areas &amp; Routing</a>
                        </li>
                        <li>
                            <a data-tmp="Controllers" asp-action="Controllers" asp-controller="Basics" asp-area=""><i class="icon icon-anchor"></i><span class="sidebar-mini-hide" />Controllers</a>
                        </li>
                        <li>
                            <a data-tmp="TagHelpers" asp-action="TagHelpers" asp-controller="Basics" asp-area=""><i class="icon icon-magic-wand"></i><span class="sidebar-mini-hide" />Tag Helpers</a>
                        </li>
                        <li>
                            <a data-tmp="EF7" asp-action="EF7" asp-controller="Basics" asp-area=""><i class="icon icon-layers"></i><span class="sidebar-mini-hide" />Entity Framework 7</a>
                        </li>
                        <li>
                            <a data-tmp="EFCore" asp-action="EFCore" asp-controller="Basics" asp-area=""><i class="icon icon-layers"></i><span class="sidebar-mini-hide" />Entity Framework Core</a>
                        </li>
                        <li>
                            <a data-tmp="Logging" asp-action="Logging" asp-controller="Basics" asp-area=""><i class="icon icon-bulb"></i><span class="sidebar-mini-hide" />Logging</a>
                        </li>
                        <li class="nav-main-heading"><span class="sidebar-mini-hide">Workshop</span></li>
                        <li>
                            <a data-tmp="Step1" asp-action="Step1" asp-controller="Home" asp-area="Workshop"><i class="fa fa-star"></i><span class="sidebar-mini-hide" />Step 1</a>
                        </li>
                        <li>
                            <a data-tmp="Step2" asp-action="Step2" asp-controller="Home" asp-area="Workshop"><i class="fa fa-star"></i><span class="sidebar-mini-hide" />Step 2</a>
                        </li>
                        <li>
                            <a data-tmp="Step3" asp-action="Step3" asp-controller="Home" asp-area="Workshop"><i class="fa fa-star"></i><span class="sidebar-mini-hide" />Step 3</a>
                        </li>
                        <li>
                            <a data-tmp="Step4" asp-action="Step4" asp-controller="Home" asp-area="Workshop"><i class="fa fa-star"></i><span class="sidebar-mini-hide" />Step 4</a>
                        </li>
                        <li>
                            <a data-tmp="Step5" asp-action="Step5" asp-controller="Home" asp-area="Workshop"><i class="fa fa-star"></i><span class="sidebar-mini-hide" />Step 5</a>
                        </li>
                        <li class="nav-main-heading"><span class="sidebar-mini-hide">OFFICIAL HELP</span></li>
                        <li>
                            <a target="_blank" href="https://docs.asp.net/en/latest/"><i class="fa fa-windows"></i><span class="sidebar-mini-hide">ASP.NET Core</span></a>
                        </li>
                        <li>
                            <a target="_blank" href="http://ef.readthedocs.io/en/latest/"><i class="fa fa-database"></i><span class="sidebar-mini-hide">Entity Framework</span></a>
                        </li>
                        <li>
                            <a target="_blank" href="http://bower.io/"><i class="fa fa-cubes"></i><span class="sidebar-mini-hide">Bower</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>
        <header id="header-navbar" class="content-mini content-mini-full">
            <ul class="nav-header pull-left">
                <li class="hidden-md hidden-lg">
                    <button class="btn btn-default" data-toggle="layout" data-action="sidebar_toggle" type="button">
                        <i class="fa fa-navicon"></i>
                    </button>
                </li>
                <li class="hidden-xs hidden-sm">
                    <button class="btn btn-default" data-toggle="layout" data-action="sidebar_mini_toggle" type="button">
                        <i class="fa fa-ellipsis-v"></i>
                    </button>
                </li>
            </ul>
        </header>
        <main id="main-container">
            <div class="content bg-image overflow-hidden" style="background-image: url('@Url.Content("~/images/photo3@2x.jpg")');">
                <div class="push-50-t push-15">
                    <h1 class="h2 text-white animated zoomIn">Modern Web Technologies</h1>
                    <h2 class="h5 text-white-op animated zoomIn">OTS 2016</h2>
                </div>
            </div>
            @RenderBody()
        </main>
        <footer id="page-footer" class="content-mini content-mini-full font-s12 bg-gray-lighter clearfix">
            <div class="pull-right">
                Crafted with <i class="fa fa-heart text-city"></i> by <a class="font-w600" href="http://www.adora-med.com" target="_blank">Adora-med</a>
            </div>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>